### PR TITLE
Chaco case study

### LINKED ISSUE #80: The Quiet Life Title too low
Case Study Title too low

screen shot 2017-05-09 at 2 47 27 pm

### PR DESCRIPTION
**Pull request by kenworthyc**
adds new chaco case study (url: `/work/chacos`).

waiting on gif versions of all videos from Connor, will add them as soon as they come in.

also adds another version of laying out iphones, one layered over another.

Resolves #80 with commit `826c0b0`. Edit: Then resolves it slightly better with `dc25b0a`.

### CODE REVIEW

**Comment by krispy1298** [comment]
@kenworthyc do you think the content is diff enough for a URL change?

**Comment by kenworthyc** [comment]
@krispy1298 I used `/work/chacos` as a way to avoid the cache clash, but the content isn't too different. The copy has been pared down, and the number of images too. Do you think we should overwrite `/work/chaco` instead?

(The actual Chaco website itself is at chacos.com, for what it's worth– that's how I chose the url.)

**Comment by krispy1298** [comment]
Let's keep the old url, unless we're gonna send a newsletter about it.

**Comment by kenworthyc** [comment]
@krispy1298 case study is at `/work/chaco`, old styles are murdered, and gifs are in!

**Comment by krispy1298** [comment]
@kenworthyc did you update the next and previous (next button that leads to chaco) buttons?

**Comment by kenworthyc** [comment]
@krispy1298 link destination changed and sizes added.

**Pull request merged**
